package ebpf_tc

import (
	"github.com/k8spacket/k8spacket/internal/broker"
	"github.com/vishvananda/netlink"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -go-package ebpf_tc tc ./bpf/tc.bpf.c

type EbpfTc struct {
	Broker broker.Broker
}

func (ebpfTc *EbpfTc) Init(iface string) {
	_ = "STUB: not implemented"

	// Load pre-compiled programs and maps into the kernel.
	return
}

// get the file descriptor of the tc_filter program

// get link device by name (network interface name)

// qdisc clsact - queueing discipline (qdisc) parent of ingress and egress filters

// try to delete previous added clsact qdisc on specific network interface, equivalent `tc qdisc del dev {{iface}} clsact`

// add clsact qdisc on specific network interface, equivalent `tc qdisc add dev {{iface}} clsact`
// check `qdisc show dev {{iface}}`

// add ingress filter

// add egress filter

// create new reader for perf events

// tcTlsHandshakeEvent is generated by bpf2go and represents perf event type in eBPF program

// Parse the perf event into a tcTlsHandshakeEvent structure.

// graceful shutdown

func addFilter(link netlink.Link, programFD int, parent uint32) {
	_ = "STUB: not implemented"

	// filter attrs
	return
}

// bpf filter struct

// add ingress/egress filter, equivalent `tc filter add dev {{iface}} [ingress|egress]`
// check `tc filter show dev {{iface}} [ingress|egress]`

func distribute(event tcTlsHandshakeEvent, tc *EbpfTc) { _ = "STUB: not implemented"; return }
