// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf_tc

import (
	_ "embed"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcTlsHandshakeEvent struct {
	_                 structs.HostLayout
	Saddr             uint32
	Daddr             uint32
	Sport             uint16
	Dport             uint16
	TlsVersion        uint16
	TlsVersionsLength uint8
	_                 [1]byte
	TlsVersions       [8]uint16
	CiphersLength     uint16
	Ciphers           [100]uint16
	ServerNameLength  uint16
	ServerName        [100]uint8
	UsedTlsVersion    uint16
	UsedCipher        uint16
}

// loadTc returns the embedded CollectionSpec for tc.
func loadTc() (*ebpf.CollectionSpec, error) { _ = "STUB: not implemented"; return nil, nil }

// loadTcObjects loads tc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcObjects
//	*tcPrograms
//	*tcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// tcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcSpecs struct {
	tcProgramSpecs
	tcMapSpecs
	tcVariableSpecs
}

// tcProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcProgramSpecs struct {
	TcFilter *ebpf.ProgramSpec `ebpf:"tc_filter"`
}

// tcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	OutputEvents *ebpf.MapSpec `ebpf:"output_events"`
}

// tcVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcVariableSpecs struct {
}

// tcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcObjects struct {
	tcPrograms
	tcMaps
	tcVariables
}

func (o *tcObjects) Close() error { _ = "STUB: not implemented"; return nil }

// tcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	OutputEvents *ebpf.Map `ebpf:"output_events"`
}

func (m *tcMaps) Close() error { _ = "STUB: not implemented"; return nil }

// tcVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcVariables struct {
}

// tcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcPrograms struct {
	TcFilter *ebpf.Program `ebpf:"tc_filter"`
}

func (p *tcPrograms) Close() error { _ = "STUB: not implemented"; return nil }

func _TcClose(closers ...io.Closer) error { _ = "STUB: not implemented"; return nil }

// Do not access this directly.
//
//go:embed tc_bpfeb.o
var _TcBytes []byte
