// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/nodegraph/model/model.proto

package model

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Src            string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	SrcName        string                 `protobuf:"bytes,2,opt,name=srcName,proto3" json:"srcName,omitempty"`
	SrcNamespace   string                 `protobuf:"bytes,3,opt,name=srcNamespace,proto3" json:"srcNamespace,omitempty"`
	Dst            string                 `protobuf:"bytes,4,opt,name=dst,proto3" json:"dst,omitempty"`
	DstName        string                 `protobuf:"bytes,5,opt,name=dstName,proto3" json:"dstName,omitempty"`
	DstNamespace   string                 `protobuf:"bytes,6,opt,name=dstNamespace,proto3" json:"dstNamespace,omitempty"`
	ConnCount      int64                  `protobuf:"varint,7,opt,name=connCount,proto3" json:"connCount,omitempty"`
	ConnPersistent int64                  `protobuf:"varint,8,opt,name=connPersistent,proto3" json:"connPersistent,omitempty"`
	BytesSent      float64                `protobuf:"fixed64,9,opt,name=bytesSent,proto3" json:"bytesSent,omitempty"`
	BytesReceived  float64                `protobuf:"fixed64,10,opt,name=bytesReceived,proto3" json:"bytesReceived,omitempty"`
	Duration       float64                `protobuf:"fixed64,11,opt,name=duration,proto3" json:"duration,omitempty"`
	MaxDuration    float64                `protobuf:"fixed64,12,opt,name=maxDuration,proto3" json:"maxDuration,omitempty"`
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=lastSeen,proto3" json:"lastSeen,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionItem) Reset() { _ = "STUB: not implemented"; return }

func (x *ConnectionItem) String() string { _ = "STUB: not implemented"; return "" }

func (*ConnectionItem) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ConnectionItem) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ConnectionItem.ProtoReflect.Descriptor instead.
func (*ConnectionItem) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ConnectionItem) GetSrc() string { _ = "STUB: not implemented"; return "" }

func (x *ConnectionItem) GetSrcName() string { _ = "STUB: not implemented"; return "" }

func (x *ConnectionItem) GetSrcNamespace() string { _ = "STUB: not implemented"; return "" }

func (x *ConnectionItem) GetDst() string { _ = "STUB: not implemented"; return "" }

func (x *ConnectionItem) GetDstName() string { _ = "STUB: not implemented"; return "" }

func (x *ConnectionItem) GetDstNamespace() string { _ = "STUB: not implemented"; return "" }

func (x *ConnectionItem) GetConnCount() int64 { _ = "STUB: not implemented"; return 0 }

func (x *ConnectionItem) GetConnPersistent() int64 { _ = "STUB: not implemented"; return 0 }

func (x *ConnectionItem) GetBytesSent() float64 { _ = "STUB: not implemented"; return 0 }

func (x *ConnectionItem) GetBytesReceived() float64 { _ = "STUB: not implemented"; return 0 }

func (x *ConnectionItem) GetDuration() float64 { _ = "STUB: not implemented"; return 0 }

func (x *ConnectionItem) GetMaxDuration() float64 { _ = "STUB: not implemented"; return 0 }

func (x *ConnectionItem) GetLastSeen() *timestamppb.Timestamp {
	_ = "STUB: not implemented"
	return nil
}

var File_internal_proto_nodegraph_model_model_proto protoreflect.FileDescriptor

const file_internal_proto_nodegraph_model_model_proto_rawDesc = "" +
	"\n" +
	"*internal/proto/nodegraph/model/model.proto\x12\x15proto.nodegraph.model\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x03\n" +
	"\x0eConnectionItem\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x18\n" +
	"\asrcName\x18\x02 \x01(\tR\asrcName\x12\"\n" +
	"\fsrcNamespace\x18\x03 \x01(\tR\fsrcNamespace\x12\x10\n" +
	"\x03dst\x18\x04 \x01(\tR\x03dst\x12\x18\n" +
	"\adstName\x18\x05 \x01(\tR\adstName\x12\"\n" +
	"\fdstNamespace\x18\x06 \x01(\tR\fdstNamespace\x12\x1c\n" +
	"\tconnCount\x18\a \x01(\x03R\tconnCount\x12&\n" +
	"\x0econnPersistent\x18\b \x01(\x03R\x0econnPersistent\x12\x1c\n" +
	"\tbytesSent\x18\t \x01(\x01R\tbytesSent\x12$\n" +
	"\rbytesReceived\x18\n" +
	" \x01(\x01R\rbytesReceived\x12\x1a\n" +
	"\bduration\x18\v \x01(\x01R\bduration\x12 \n" +
	"\vmaxDuration\x18\f \x01(\x01R\vmaxDuration\x126\n" +
	"\blastSeen\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\blastSeenB?Z=github.com/k8spacket/k8spacket/internal/proto/nodegraph/modelb\x06proto3"

var (
	file_internal_proto_nodegraph_model_model_proto_rawDescOnce sync.Once
	file_internal_proto_nodegraph_model_model_proto_rawDescData []byte
)

func file_internal_proto_nodegraph_model_model_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_internal_proto_nodegraph_model_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_nodegraph_model_model_proto_goTypes = []any{
	(*ConnectionItem)(nil),        // 0: proto.nodegraph.model.ConnectionItem
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_internal_proto_nodegraph_model_model_proto_depIdxs = []int32{
	1, // 0: proto.nodegraph.model.ConnectionItem.lastSeen:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init()                                                 { file_internal_proto_nodegraph_model_model_proto_init() }
func file_internal_proto_nodegraph_model_model_proto_init() { _ = "STUB: not implemented"; return }
