package ebpf_socketfilter

import (
	"github.com/k8spacket/k8spacket/internal/broker"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -go-package ebpf_socketfilter socketfilter ./bpf/socketfilter.bpf.c

type EbpfSocketFilter struct {
	Broker broker.Broker
}

func (ebpfSocketFilter *EbpfSocketFilter) Init() {
	_ = "STUB: not implemented"

	// Load pre-compiled programs and maps into the kernel.
	return
}

// create new reader for perf events

// socketfilterTlsHandshakeEvent is generated by bpf2go and represents perf event type in eBPF program

// Parse the perf event into a socketfilterTlsHandshakeEvent structure.

// graceful shutdown

func distribute(event socketfilterTlsHandshakeEvent, ebpfSocketFilter *EbpfSocketFilter) {
	_ = "STUB: not implemented"
	return
}
