package ebpf_inet

import (
	"github.com/k8spacket/k8spacket/internal/broker"
)

/*
bpf2go - eBPF bytecode compiler & go files generator
args:
-cc clang - select C compiler
-target native - means get target platform from golang env GOARCH
-type event - name of type in C ebpf program to generate Go declaration
-go-package -package for output go file
bpf - identity name of generating program
./bpf/inet.bpf.c - C language source file
*/
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target native -type event -go-package ebpf_inet bpf ./bpf/inet.bpf.c

type EbpfInet struct {
	Broker broker.Broker
}

func (ebpfInet *EbpfInet) Init() { _ = "STUB: not implemented"; return }

// Allow the current process to lock more memory than the default for eBPF resources. Default value is 64KB
// https://prototype-kernel.readthedocs.io/en/latest/bpf/troubleshooting.html#memory-ulimits
// requires on kernels < 5.11 to remove memlock (error: failed to set memlock rlimit: operation not permitted)

// Load pre-compiled programs and maps into the kernel.

// attach the eBPF program to the tracepoint sock/inet_sock_set_state

// create new reader for perf events

// bpfEvent is generated by bpf2go and represents perf event type in eBPF program

// Parse the perf event into a go bpfEvent structure.

// graceful shutdown

func distribute(event bpfEvent, inet *EbpfInet) { _ = "STUB: not implemented"; return }
